###
POST http://localhost:8080/v2/libraryEvents
Content-Type: application/json

{
  "eventId": null,
  "book"  :{
    "id" : 123,
    "name": "Elder Ring",
    "authorName": "Andy"
  }
}

### send event reginal
POST http://localhost:8080/v1/libraryEvents
Content-Type: application/json

{
  "eventId": null,
  "book"  :{
    "id" : 1233,
    "name": "Elder Ring",
    "authorName": "Andy"
  }
}
### send event bad request
POST http://localhost:8080/v1/libraryEvents
Content-Type: application/json

{
  "eventId": null,
  "book" :{
    "authorName": "Andy"
  }
}

###
PUT http://localhost:8080/v1/libraryEvents/{{eventId}}
