apiVersion: apps/v1
kind: Deployment
metadata:
  name: story-vol
spec:
  replicas: 2
  selector:
    matchLabels:
      app: story
  template:
    metadata:
      labels:
        app: story
    spec:
      containers:
      - name: story-vol
        image: andychentw/kube-volume-first:latest
        imagePullPolicy: Always
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 3000
        env:
          - name: STORY_PATH
            # value: story
            valueFrom:
              configMapKeyRef:
                name: story-config
                key: store-path
        volumeMounts:
          - mountPath: /app/story
            name: story-vol
      volumes:
        - name: story-vol
          # emptyDir: {}
          # hostPath:
          #   path: /data2
          #   type: DirectoryOrCreate
          persistentVolumeClaim:
            claimName: host-pvc
            
          
