
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv
spec:
  storageClassName: nfs-client
  capacity:
    storage: 900Mi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  nfs:
    server: 192.168.0.150
    path: "/volume1/K8S"
#  mountOptions:
#    - nfsvers=4.2

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-pvc
spec:
  volumeName: nfs-pv
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  storageClassName: nfs-client
  resources:
    requests:
      storage: 200Mi

