#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:8010/eureka
#
token:
#  secret: Ss9pnhMZp+dFrlasNNIWvtFOXpTYQHEYQ9OlyydBkqk=
  expired:
    time: 30

ui:
  title: HelloUUUAndy

#spring:
#  rabbitmq:
#    host: localhost
#    port: 5672
#    username: guest
#    password: guest
