apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-app
spec:
  selector:
    matchLabels:
      app: auth-app
  replicas: 1     
  template:
    metadata:
      labels:
        app: auth-app    
    spec:
      containers:
      - name: auth-app
        image: andychentw/kube-network-auth:latest
        resources:
          limits:
            memory: "128Mi"  
            cpu: "500m"
        ports:
          - containerPort: 80   
