spring:
  application:
    name: gateway-service
  config:
    import: optional:configserver:http://localhost:8010
  cloud:
    gateway:
      discovery:
        locator:
          #設定成false就只會route有設定route的path
          enabled: true
          lower-case-service-id: false
server:
  port: 8087

management:
  endpoints:
    web:
      exposure:
        include: "*"
eureka:
  instance:
    instance-id: gateway-service-${random.value}
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8011/eureka
