version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3.10-management
    mem_limit: 350m
    expose:
      - "5672"
      - "15672"
    ports:
      - 5672:5672
      - 15672:15672
    networks:
      - zipkin
    healthcheck:
      test: [ "CMD", "rabbitmqctl", "status" ]
      interval: 10s
      timeout: 5s
      retries: 10


    # https://hub.docker.com/r/openzipkin/zipkin
  zipkin:
    image: openzipkin/zipkin
    mem_limit: 512m
    expose:
      - "9411"
    ports:
      - "9411:9411"
    networks:
      - zipkin
    environment:
      - RABBIT_ADDRESSES=rabbitmq
      - RABBIT_USER=guest
      - RABBIT_PASSWORD=guest
      - STORAGE_TYPE=mem
    depends_on:
      rabbitmq:
        condition: service_healthy

networks:
  zipkin:
