apiVersion: apps/v1
kind: Deployment
metadata: 
  name: second-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: second-app
      tier: backend
  template:
    metadata:
      labels:
        app: second-app
        tier: backend
    spec:
      containers:
        - name: node-app
          image: andychentw/kub-first-app:2
