server:
  port: ${PORT:0}
spring:
  application:
    name: users-ws

#  r2dbc:
#    url: r2dbc:postgres://localhost:5432/postgres
#    username: postgres
#    password: p@ssw0rd
#    properties:
#      schema: public
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8010/eureka
  instance:
    instance-id: ${spring.application.name}:${${spring.application_name}:${random.value}}

gateway:
  ip: 192.168.0.105
token:
  secret: Ss9pnhMZp+dFrlasNNIWvtFOXpTYQHEYQ9OlyydBkqk=
  expired:
    time: 10
